allow-flight=true
difficulty=peaceful
enable-command-block=true
gamemode=creative
level-name=world
max-players=4
motd=Aetherklang Mass Content Test
online-mode=false
server-port=25585
spawn-protection=0
