allow-flight=true
enable-command-block=true
enable-rcon=true
gamemode=creative
level-name=world
max-tick-time=0
motd=Aetherklang Endgame Verification
online-mode=false
pause-when-empty-seconds=-1
rcon.password=endgame-smoke
rcon.port=25792
server-port=25791
simulation-distance=4
spawn-protection=0
view-distance=4
