extends RefCounted
## Pure stat math — 1:1 port of GOOBY/src/systems/stats.js (§C1).
##
## All numbers mirror GOOBY/src/data/constants.js (STATS + MOOD blocks).
## Every function is static and pure: dictionaries in, NEW dictionaries out.
## Stat dictionaries use the web keys verbatim: hunger/energy/hygiene/fun.
## Numeric parity is proven against tests/fixtures/golden_values.json
## (generated by tools/fixtures/make_v4_fixtures.mjs from the real web code).

const MIN := 0.0
const MAX := 100.0
const KEYS: Array[String] = ["hunger", "energy", "hygiene", "fun"]

## Decay per real minute while awake (app open or closed).
const RATES_AWAKE := {"hunger": -0.35, "energy": -0.25, "hygiene": -0.15, "fun": -0.5}
## Per real minute while asleep: hunger half rate, energy fills 0→100 in 30 min.
const RATES_ASLEEP := {"hunger": -0.175, "energy": 3.334, "hygiene": 0.0, "fun": 0.0}

const LOW_STAT := 25.0
const CRITICAL_STAT := 10.0
const EXHAUSTED_AT_OR_BELOW := 15.0
const EXHAUSTED_MOOD_CAP := 39.0

const MOOD_MIN_WEIGHT := 0.35
const MOOD_AVG_WEIGHT := 0.65
## Bands checked top-down: first entry whose min <= mood wins.
const MOOD_BANDS := [
	{"id": "ecstatic", "min": 80.0},
	{"id": "happy", "min": 60.0},
	{"id": "neutral", "min": 40.0},
	{"id": "grumpy", "min": 25.0},
	{"id": "miserable", "min": 0.0},
]


## Clamp a single stat value to [0, 100]. Non-finite/non-numeric input falls
## back to MIN (web V2/FIX-A: NaN poisoning guard).
static func clamp_stat(value: Variant) -> float:
	var n := _num(value)
	if is_nan(n) or is_inf(n):
		return MIN
	return minf(MAX, maxf(MIN, n))


## Clamp every stat of a stats dict (returns a new dict; missing keys -> 0).
static func clamp_stats(stats: Dictionary) -> Dictionary:
	var out := {}
	for k in KEYS:
		var n := _num(stats.get(k))
		out[k] = clamp_stat(0.0 if is_nan(n) else n)
	return out


## Apply one decay/fill tick (§C1 rates). Pure — returns a new stats dict.
## opts: {"asleep": bool, "rateMult": float} — rateMult 0.3 = offline sim (§E4).
static func apply_tick(stats: Dictionary, dt_min: float, opts: Dictionary = {}) -> Dictionary:
	var rates: Dictionary = RATES_ASLEEP if opts.get("asleep", false) else RATES_AWAKE
	var mult := _num(opts.get("rateMult", 1.0))
	var out := {}
	for k in KEYS:
		out[k] = clamp_stat(_num(stats.get(k)) + float(rates[k]) * dt_min * mult)
	return out


## Mood formula (§C1): 0.35 * min(stats) + 0.65 * avg(stats), 0–100.
## Exhausted (energy <= 15) caps mood at 39; opts.debuff (early-wake grumpy,
## §C1.4) is subtracted before capping.
static func mood(stats: Dictionary, opts: Dictionary = {}) -> float:
	var lowest := INF
	var sum := 0.0
	for k in KEYS:
		var v := _num(stats.get(k))
		lowest = minf(lowest, v)
		sum += v
	var avg := sum / KEYS.size()
	var m := MOOD_MIN_WEIGHT * lowest + MOOD_AVG_WEIGHT * avg
	m -= _num(opts.get("debuff", 0.0))
	if _num(stats.get("energy")) <= EXHAUSTED_AT_OR_BELOW:
		m = minf(m, EXHAUSTED_MOOD_CAP)
	return minf(MAX, maxf(MIN, m))


## Mood band id for a mood value (§C1 bands).
static func mood_band(mood_value: float) -> String:
	for band: Dictionary in MOOD_BANDS:
		if mood_value >= float(band["min"]):
			return band["id"]
	return "miserable"


## True when the stat is in the "low" band (< 25, §C1).
static func is_low(value: float) -> bool:
	return value < LOW_STAT


## True when the stat is critical (< 10, §C1).
static func is_critical(value: float) -> bool:
	return value < CRITICAL_STAT


## True when Gooby is exhausted (energy <= 15 → minigames refuse, §C1).
static func is_exhausted(stats: Dictionary) -> bool:
	return _num(stats.get("energy")) <= EXHAUSTED_AT_OR_BELOW


## Apply stat deltas (food, wash, ...) with clamping. Pure — new dict.
static func apply_deltas(stats: Dictionary, deltas: Dictionary) -> Dictionary:
	var out := {}
	for k in KEYS:
		out[k] = clamp_stat(_num(stats.get(k)) + _num(deltas.get(k, 0.0)))
	return out


## Lenient numeric read (mirrors JS Number() for the types JSON can carry).
static func _num(value: Variant) -> float:
	match typeof(value):
		TYPE_INT, TYPE_FLOAT:
			return float(value)
		TYPE_BOOL:
			return 1.0 if value else 0.0
		_:
			return NAN
